name: CI/CD

on:
  push:
    branches: [deploy-test]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t seriushub/employeemanager .
      - name: Publish image to Docker Hub
        run: docker push seriushub/employeemanager:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    secrets:
      MYSQL_HOST: ${{secrets.MYSQL_HOST}}
      MYSQL_USER: ${{secrets.MYSQL_USER}}
      MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
      MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}
    steps:
      - name: Pull Images form Docker Hub
        run: docker pull seriushub/employeemanager:latest
      - name: Delete Old Container
        run: docker rm -f employee-manager-container
      - name: Run Docker Container
        run: |
          docker run -d \
            -p 8080:8080 \
            --name employee-manager-container \
            --secret MYSQL_HOST \
            --secret MYSQL_USER \
            --secret MYSQL_PASSWORD \
            --secret MYSQL_DATABASE \
            seriushub/employeemanager

